# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GD_fun <- function(a, b, ay, tmp, u, mcov_j, pos, d2, family) {
    invisible(.Call(`_eiv_GD_fun`, a, b, ay, tmp, u, mcov_j, pos, d2, family))
}

shrink_est <- function(lb, m, n, X, Y, beta, mcov, pos, v, family) {
    .Call(`_eiv_shrink_est`, lb, m, n, X, Y, beta, mcov, pos, v, family)
}

rcpp_mcesteqn <- function(lb, m, n, X, Y, beta, mcov, ind, modify_inv, family) {
    .Call(`_eiv_rcpp_mcesteqn`, lb, m, n, X, Y, beta, mcov, ind, modify_inv, family)
}

calculate_G <- function(lb, m, n, X, Y, beta, mcov, ind, acov, vinv, us, d, family) {
    .Call(`_eiv_calculate_G`, lb, m, n, X, Y, beta, mcov, ind, acov, vinv, us, d, family)
}

rcpp_inference <- function(lb, m, n, X, Y, beta, mcov, ind, finsam_cor, modify_inv, family) {
    .Call(`_eiv_rcpp_inference`, lb, m, n, X, Y, beta, mcov, ind, finsam_cor, modify_inv, family)
}

