# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nearPD <- function(m, maxit, eig_tol, conv_tol) {
    .Call(`_eiv_nearPD`, m, maxit, eig_tol, conv_tol)
}

rcpp_mcesteqn <- function(lb, m, n, X, Y, beta, mcov, ind, maxit, eig_tol, conv_tol, modify_inv) {
    .Call(`_eiv_rcpp_mcesteqn`, lb, m, n, X, Y, beta, mcov, ind, maxit, eig_tol, conv_tol, modify_inv)
}

rcpp_inference <- function(lb, m, n, X, Y, beta, mcov, ind, maxit, eig_tol, conv_tol, modify_inv) {
    .Call(`_eiv_rcpp_inference`, lb, m, n, X, Y, beta, mcov, ind, maxit, eig_tol, conv_tol, modify_inv)
}

